# Conclusion

In 2002, a study published by Norman Nie and Lutz Erbring from Stanford describes the internet as a "giant public library with a decidedly commercial tilt." The study found that only 38% of Americans over 18 accessed the internet at home, and a max 55% of adults have access to the internet at all. The paper proceeds to claim that the more people use the internet, the less time they spend with friends and families.^[[Interent and Society](http://www.nomads.usp.br/documentos/textos/cultura_digital/tics_arq_urb/internet_society%20report.pdf)]

In 2019, we see a dramatic rise in the number of people that have access to internet at home to over 80%. Most people spend their time on the interent on YouTube and Facebook, two sites that are very much about connecting people from all over the globe. The data in this survey do not point to a trend of losing pysical touch with other humans, but it does point to the desire to gain a digital touch. 

We saw that social media is more easy to give up than the internet, however we also saw that even people who claim they do not use the internet very frequenyly primarily spend their time on social media sites. There is a discrepency in this. How can people be primarity using social media sites but at the same time be so willing to give it up? This seemingly paradoxical idea suggests that people know something new will always come around. They may be willing to give up the current sites, but if the question had been phrased in such a way that social media would be lost to them forever, we believe the reponses would have been very much shifted towards the "impossible" answer. 

Almost all Americans use the internet regardless of background. While this is not a monumental discovery, it is important. This means that as people become more and more connected, the people that are not want to join in. The connectivity created by the internet inspires everyone around it to become invested. The only major difference in usage comes from age. Young people spread out there usage of the internet over many applications, while older people mostly stick to Facebook. This hints at two possibilities, Facebook is a highly inticive app that brings people of all ages to it, or Facebook is simple enough that it becomes accessible to many different technical backgrounds. It is most likely a combination of the two, the basic functionality of Facebook is very simple, but also effective.

Lastly, the internet has its pros and cons, and while some people believe it be a hinderence, most believe it is very positive for society. This is evident by the sheer growth of internet users from the small 2 node network created by the original ARPANET, to the almost 4.4 billion users world wide today.^[https://wearesocial.com/blog/2019/01/digital-2019-global-internet-use-accelerates] Information and people, these are the most used words when discribing the internet, but for both good and bad. Free information leads to knowladge but restricted information leads to hacking. People created a connected digital world, but some use the internet to bully. Most if not all of the great aspects of the internet also have a negative effect, but just like any other manmade creation, the internet is just a tool. And it comes down to how people use that tool that will determine the success of the internet. 


