---
output:
  html_document: default
  pdf_document: default
---
# Missing Values

Missing Values

```{r}
library(ggplot2) 
library(dplyr)
library(tidyverse)
library(mi) 
#devtools::install_github('https://github.com/cran/extracat') 
#devtools::install_github("CRAN/extracat")
library(extracat)
library("imputeTS")
```



```{r message=FALSE, warning=FALSE}
core_trends_raw = readr::read_csv("../data/tidy/core_trends.csv")
```


```{r}
core_trends= core_trends_raw %>%
  select(year,respid,cregion,state,age,education,employment,house.income,pol.party,sex,race,internet.freq,contains('sm.use'),contains('society'),contains('depend')) %>%
   select(-sm.use.reddit)
core_trends=as.data.frame(core_trends)
```


```{r message=FALSE, warning=FALSE}
ct_mi <- mi::missing_data.frame( core_trends)
```

```{r}
image(ct_mi)
```

```{r}
pattarn = ct_mi@patterns  
levels(pattarn)
```

 

```{r fig.height=10, fig.width=14}
extracat::visna(core_trends, sort="b") + theme_gray(16)
```

Respondents who declined to answer or do not know the answers.


```{r}
trends <- na.replace(core_trends, 0)
 
trends = trends %>% select(-year,-respid,-cregion,-state,-society.text,-sex)
 
trends$age[trends$age %in% c(98,99)] <- NA
trends$education[trends$education %in% c(98,99)] <- NA
trends$education[trends$education %in% c(98,99)] <- NA
trends$house.income[trends$house.income %in% c(98,99)] <- NA
trends$pol.party[trends$pol.party %in% c(8,9)] <- NA
trends$race[trends$race %in% c(8,9)] <- NA
trends$internet.freq[trends$internet.freq %in% c(8,9)] <- NA
trends$sm.use[trends$sm.use %in% c(8,9)] <- NA
trends$sm.use.twitter[trends$sm.use.twitter %in% c(8,9)] <- NA
trends$sm.use.instagram[trends$sm.use.instagram %in% c(8,9)] <- NA
trends$sm.use.facebook[trends$sm.use.facebook %in% c(8,9)] <- NA
trends$sm.use.snapchat[trends$sm.use.snapchat %in% c(8,9)] <- NA
trends$sm.use.youtube[trends$sm.use.youtube %in% c(8,9)] <- NA
trends$sm.use.whatsapp[trends$sm.use.whatsapp %in% c(8,9)] <- NA
trends$sm.use.pintrest[trends$sm.use.pintrest %in% c(8,9)] <- NA
trends$sm.use.linkedin[trends$sm.use.linkedin %in% c(8,9)] <- NA

trends$society.overall[trends$society.overall %in% c(8,9)] <- NA
trends$society.personal[trends$society.personal %in% c(8,9)] <- NA

trends$depend.cellphone[trends$depend.cellphone %in% c(8,9)] <- NA
trends$depend.television[trends$depend.television %in% c(8,9)] <- NA
trends$depend.internet[trends$depend.internet %in% c(8,9)] <- NA
trends$depend.sm[trends$depend.sm %in% c(8,9)] <- NA
```

```{r fig.height=12, fig.width=14}
extracat::visna(trends, sort="b") + theme_gray(16)
```


